# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5fd665939236eb5f0d87cc67b93e4f436308050f9ebde996b34c12194b1f78cdafeeb4a02e7f1b971416c8f2a2ff6270fb81650f1990c91fb471a4b3fb0894

test:
  secret_key_base: 38bf1d143e4e32aaa9367d74ad497e694f30b6b7d19e696b533c8f2e1eea4016508061026b90677251e7e682233bb581895f719e36d8a66089d40db5db82c669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
